routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'service',
    'as' => 'service.'

],function(){
    Route::get('/','ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::post('/store','ServiceController@store')->name('store');
    Route::get('/show/{service}','ServiceController@show')->name('show');
    Route::get('/edit/{service}','ServiceController@edit')->name('edit');
    Route::post('/update/{service}','ServiceController@update')->name('update');
    Route::get('/destroy/{service}','ServiceController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'doctor',
    'as' => 'doctor.'

],function(){
    Route::get('/','DoctorController@index')->name('index');
    Route::get('/create','DoctorController@create')->name('create');
    Route::post('/store','DoctorController@store')->name('store');
    Route::get('/ajax_res/{doctor}','DoctorController@ajax_res')->name('respond');
    Route::get('/show/{doctor}','DoctorController@show')->name('show');
    Route::get('/edit/{doctor}','DoctorController@edit')->name('edit');
    Route::post('/update/{doctor}','DoctorController@update')->name('update');
    Route::get('/destroy/{doctor}','DoctorController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'company',
    'as' => 'company.'

],function(){
    Route::get('/','CompanyController@index')->name('index');
    Route::get('/create','CompanyController@create')->name('create');
    Route::post('/store','CompanyController@store')->name('store');
    Route::get('/show/{company}','CompanyController@show')->name('show');
    Route::get('/edit/{company}','CompanyController@edit')->name('edit');
    Route::post('/update/{company}','CompanyController@update')->name('update');
    Route::get('/destroy/{company}','CompanyController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'patient',
    'as' => 'patient.'

],function(){
    Route::get('/','PatientController@index')->name('index');
    Route::get('/create','PatientController@create')->name('create');
    Route::post('/store','PatientController@store')->name('store');
    Route::get('/show/{patient}','PatientController@show')->name('show');
    Route::get('/edit/{patient}','PatientController@edit')->name('edit');
    Route::post('/update/{patient}','PatientController@update')->name('update');
    Route::get('/destroy/{patient}','PatientController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'invoice',
    'as' => 'invoice.'

],function(){
    Route::get('/','InvoiceController@index')->name('index');
    Route::get('/create/{patient}','InvoiceController@create')->name('create');
    Route::post('/store','InvoiceController@store')->name('store');
    Route::get('/show/{invoice}','InvoiceController@show')->name('show');
    Route::get('/edit/{id}','InvoiceController@edit')->name('edit');
    Route::post('/update/{id}','InvoiceController@update')->name('update');
    Route::get('/destroy/{invoice}','InvoiceController@destroy')->name('destroy');
});

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    public function invoice_items() {
        return $this->hasMany(Invoice_Item::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function services(){
        return $this->belongsToMany(Service::class, 'doctor_service');
    }
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use App\Doctor;
use Illuminate\Http\Request;
use Auth;

class DoctorController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $doctors = Doctor::all();
        return view('doctors.index')->with('doctors' , $doctors);
    }

    public function ajax_res(Doctor $doctor)
    {
       // $doctor = Doctor::find($id);
        $services = $doctor->services;

        return $services;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services = Service::all();
        return view('doctors.create')->with('services', $services);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'age' => 'required | numeric',
            'services' => 'required'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط'
        ];

        $this->validate($request, $rules, $messages);

        $doctor = new Doctor;
        $doctor->name = $request->input('name');
        $doctor->age = $request->input('age');
        $doctor->user_id = $request->input('user_id');
        $doctor->save();
        $doctor->services()->sync($request->services);

        return redirect()->route('doctor.index')->with('success', 'تم إضافة طبيب بنجاح');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Doctor $doctor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Doctor $doctor)
    {
       // $doctor = Doctor::find($id);
       // $services = Service::all()->except($doctor->services()->pluck('id')->toArray());
      //  $doc_services = $doctor->services()->pluck('service_id')->toArray();
        $doc_services = $doctor->services;
        $all_services = Service::all();

       return view('doctors.edit')->with(['doctor' => $doctor, 'all_services' => $all_services, 'doc_services' => $doc_services]);
        // return view('doctors.edit')->with(['doctor' => $doctor, 'all_services' => $all_services]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Doctor $doctor)
    {
       // dd($request);
        $rules = [
            'name' => 'required',
            'age' => 'required | numeric'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط'
        ];

        $this->validate($request, $rules, $messages);

    //    $doctor = Doctor::find($id);
        $doctor->name = $request->input('name');
        $doctor->age = $request->input('age');
        $doctor->user_id = $request->input('user_id');
        $doctor->save();
        $doctor->services()->sync($request->services);

        return redirect()->route('doctor.index')->with('success', 'تم تخزين التعديلات');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
      //  $doctor = Doctor::find($id);
        $doctor->delete();

        return redirect()->route('doctor.index')->with('success', 'تم إزالة الطبيب بنجاح');
    }
}

resources/views/doctors/create.blade.php
@extends('layouts.app')

@section('title')
    إضافة طبيب
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">إضافة طبيب</div>
            <div class="card-body">
            <form action="{{ route('doctor.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-5">
                <label for="name" class="float-right">إسم طبيب</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم الطبيب" value="{{ old('name') }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-5">
                    <label for="age" class="float-right">العمر</label>
                    <input type="text" name="age" id="age" placeholder="أدخل عمر الطبيب" value="{{ old('age') }}" class="form-control">
                    @if ($errors->has('age'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('age') }}</strong>
                        </span>
                    @endif
                        </div>
                </div>
                <hr>
                <div class="row">
                        <div class="checkbox">
                            <table class="table" style="margin-right: 15px;">
                                <h5 class="pull-right" style="margin-right: 15px;">الخدمات</h5>
                                <tr>
                                @foreach ($services as $service)
                                <td><input type='checkbox' name="services[]" value="{{ $service->id }}" /> {{$service->name}} </td>
                                @endforeach
                                </tr>
                                @if ($errors->has('services'))
                                    <span class="float-right alert-danger">
                                         <strong>{{ $errors->first('services') }}</strong>
                                    </span>
                                @endif
                            </table>
                        </div>
                        <hr>
                        <div class="col-2">
                            <input type="hidden" name="user_id" value="{{Auth::id()}}">
                            <input type="submit" value="حفظ" class="form-control btn btn-primary">
                            </div>
                </div>


            </form>
            </div>
    </div>
@endsection

resources/views/doctors/edit.blade.php
@extends('layouts.app')

@section('title')
    تعديل طبيب
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">تعديل طبيب</div>
            <div class="card-body">
            <form action="{{ route('doctor.update',['id'=>$doctor->id]) }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-5">
                <label for="name" class="float-right">إسم طبيب</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم الطبيب" value="{{ $doctor->name }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-5">
                    <label for="age" class="float-right">العمر</label>
                    <input type="text" name="age" id="age" placeholder="أدخل عمر الطبيب" value="{{ $doctor->age }}" class="form-control">
                    @if ($errors->has('age'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('age') }}</strong>
                        </span>
                    @endif
                        </div>
                </div>
                <hr>
                    <div class="row">
                        <div class="checkbox">
                            <table class="table" style="margin-right: 15px;">
                                <h5 class="pull-right" style="margin-right: 15px;">الخدمات الذي يقدمها</h5>
                                <tr>
                                    @foreach ($all_services as $service)
                                    <td><input type='checkbox'
                                            {{ in_array($service->id, $doc_services->pluck('id')->toArray()) ? 'checked' : ''}}
                                            name="services[]" value="{{ $service->id }}" />  {{$service->name}}</td>
                                    @endforeach
                                </tr>
                            </table>
                        </div>
                    </div>
                <hr>
                <div class="col-2">
                <input type="hidden" name="user_id" value="{{Auth::id()}}">
                <input type="submit" value="حفظ" class="form-control btn btn-primary">
                </div>

            </form>
            </div>
    </div>
@endsection

resources/views/doctors/index.blade.php
@extends('layouts.app')

@section('title')
    الأطباء
@endsection
@section('content')

<div class="container card" dir="rtl">
        {{-- <a href="{{ route('service.create') }}" class="btn btn-primary">إضافة خدمة</a> --}}
    <table class="table table-striped table-bordered" style="margin-bottom: 0px; margin-top: 10px;">
        <tr>
            <td align="center"><strong>#</strong></td>
            <td align="center"><strong>الاسم</strong></td>
            <td align="center"><strong>العمر</strong></td>
            <td align="center"><strong>أُضيف بواسطة</strong></td>
            <td align="center"><strong>الخدمات الذي يقدمها</strong></td>
            <td align="center"><strong>عمليات</strong></td>
        </tr>
        @forelse ($doctors as $doctor)

                    <tr>
                        <td align="center">{{ ++$loop->index }}</td>
                        <td align="center">{{ $doctor->name }}</td>
                        <td align="center">{{ $doctor->age }}</td>
                        <td align="center">{{ $doctor->user->name }}</td>
                        <td align="center">
                            @foreach ($doctor->services as $service)
                                {{$service->name}} -
                            @endforeach
                        </td>
                        <td align="center">
                            <a href="{{ route('doctor.edit',['doctor'=>$doctor->id]) }}" class=" btn btn-warning">تعديل</a>
                            <a href="{{ route('doctor.destroy',['doctor'=>$doctor->id]) }}" class="btn btn-danger" onclick="return confirm('هل تريد أن تحذف هذا الطبيب ؟')">حذف</a>
                        </td>
                    </tr>

                @empty
                    <tr colspan="4">لا يوجد أطباء</tr>
            @endforelse
        </table>
        <hr>
        <div class="row">
            <div class="col-2">
                <a href="{{ route('doctor.create') }}" class="btn btn-primary" style="margin-bottom:10px;">إضافة طبيب</a>
            </div>
        </div>
</div>
@endsection