routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'service',
    'as' => 'service.'

],function(){
    Route::get('/','ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::post('/store','ServiceController@store')->name('store');
    Route::get('/show/{service}','ServiceController@show')->name('show');
    Route::get('/edit/{service}','ServiceController@edit')->name('edit');
    Route::post('/update/{service}','ServiceController@update')->name('update');
    Route::get('/destroy/{service}','ServiceController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'doctor',
    'as' => 'doctor.'

],function(){
    Route::get('/','DoctorController@index')->name('index');
    Route::get('/create','DoctorController@create')->name('create');
    Route::post('/store','DoctorController@store')->name('store');
    Route::get('/ajax_res/{doctor}','DoctorController@ajax_res')->name('respond');
    Route::get('/show/{doctor}','DoctorController@show')->name('show');
    Route::get('/edit/{doctor}','DoctorController@edit')->name('edit');
    Route::post('/update/{doctor}','DoctorController@update')->name('update');
    Route::get('/destroy/{doctor}','DoctorController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'company',
    'as' => 'company.'

],function(){
    Route::get('/','CompanyController@index')->name('index');
    Route::get('/create','CompanyController@create')->name('create');
    Route::post('/store','CompanyController@store')->name('store');
    Route::get('/show/{company}','CompanyController@show')->name('show');
    Route::get('/edit/{company}','CompanyController@edit')->name('edit');
    Route::post('/update/{company}','CompanyController@update')->name('update');
    Route::get('/destroy/{company}','CompanyController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'patient',
    'as' => 'patient.'

],function(){
    Route::get('/','PatientController@index')->name('index');
    Route::get('/create','PatientController@create')->name('create');
    Route::post('/store','PatientController@store')->name('store');
    Route::get('/show/{patient}','PatientController@show')->name('show');
    Route::get('/edit/{patient}','PatientController@edit')->name('edit');
    Route::post('/update/{patient}','PatientController@update')->name('update');
    Route::get('/destroy/{patient}','PatientController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'invoice',
    'as' => 'invoice.'

],function(){
    Route::get('/','InvoiceController@index')->name('index');
    Route::get('/create/{patient}','InvoiceController@create')->name('create');
    Route::post('/store','InvoiceController@store')->name('store');
    Route::get('/show/{invoice}','InvoiceController@show')->name('show');
    Route::get('/edit/{id}','InvoiceController@edit')->name('edit');
    Route::post('/update/{id}','InvoiceController@update')->name('update');
    Route::get('/destroy/{invoice}','InvoiceController@destroy')->name('destroy');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    public function patients(){
        return $this->hasMany(Patient::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Service;
use App\Doctor;
use Illuminate\Http\Request;
use Auth;

class CompanyController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        return view('companies.index')->with('companies' , $companies);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'cover_percentage' => 'required | numeric | between:0,100'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط',
            'between' => 'يجب ان تكون النسبة بين 0 - 100'
        ];

        $this->validate($request, $rules, $messages);

        $company = new Company;
        $company->name = $request->input('name');
        $company->cover_percentage = $request->input('cover_percentage');
        $company->user_id = $request->input('user_id');
        $company->save();

        return redirect()->route('company.index')->with('success', 'تم إضافة الشركة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
   //     $company = Company::find($id);

        return view('companies.edit')->with('company', $company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        $rules = [
            'name' => 'required',
            'cover_percentage' => 'required | numeric | between:0,100'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط',
            'between' => 'يجب ان تكون النسبة بين 0 - 100'
        ];

        $this->validate($request, $rules, $messages);

     //   $company = Company::find($id);
        $company->name = $request->input('name');
        $company->cover_percentage = $request->input('cover_percentage');
        $company->user_id = $request->input('user_id');
        $company->save();

        return redirect()->route('company.index')->with('success', 'تم تخزين التعديلات');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
    //    $company = Company::find($id);
        $company->delete();

        return redirect()->route('company.index')->with('success', 'تم إزالة الشركة بنجاح');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('title')
    إضافة شركة
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">إضافة شركة</div>
            <div class="card-body">
            <form action="{{ route('company.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-5">
                <label for="name" class="float-right">إسم الشركة</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم الشركة" value="{{ old('name') }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-5">
                    <label for="age" class="float-right">نسبة التغطية للتكاليف (المئوية)</label>
                    <input type="text" name="cover_percentage" id="cover_percentage" placeholder="نسبة التغطية للتكاليف" value="{{ old('cover_percentage') }}" class="form-control">
                    @if ($errors->has('cover_percentage'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('cover_percentage') }}</strong>
                        </span>
                    @endif
                        </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-2">
                            <input type="hidden" name="user_id" value="{{Auth::id()}}">
                            <input type="submit" value="حفظ" class="form-control btn btn-primary">
                            </div>
                </div>


            </form>
            </div>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('title')
    تعديل شركة
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">تعديل شركة</div>
            <div class="card-body">
            <form action="{{ route('company.update',['id'=>$company->id]) }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-5">
                <label for="name" class="float-right">إسم الشركة</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم الشركة" value="{{ $company->name }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-5">
                    <label for="age" class="float-right">نسبة التغطية للتكاليف (المئوية)</label>
                    <input type="text" name="cover_percentage" id="cover_percentage" placeholder="نسبة التغطية للتكاليف" value="{{ $company->cover_percentage }}" class="form-control">
                    @if ($errors->has('cover_percentage'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('cover_percentage') }}</strong>
                        </span>
                    @endif
                        </div>
                </div>
                <hr>
                <div class="row">
                        <div class="col-2">
                            <input type="hidden" name="user_id" value="{{Auth::id()}}">
                            <input type="submit" value="حفظ" class="form-control btn btn-primary">
                            </div>
                </div>


            </form>
            </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('title')
    الشركات
@endsection
@section('content')

</div>
<div class="container card" dir="rtl">
        {{-- <a href="{{ route('service.create') }}" class="btn btn-primary">إضافة خدمة</a> --}}
    <table class="table table-striped table-bordered" style="margin-bottom: 0px; margin-top: 10px;">
        <tr>
            <td align="center"><strong>#</strong></td>
            <td align="center"><strong>اسم الشركة</strong></td>
            <td align="center"><strong>نسبة التغطية للتكاليف (المئوية)</strong></td>
            <td align="center"><strong>أُضيفت بواسطة</strong></td>
            <td align="center"><strong>عمليات</strong></td>
        </tr>
        @forelse ($companies as $company)

                    <tr>
                        <td align="center">{{ ++$loop->index }}</td>
                        <td align="center">{{ $company->name }}</td>
                        <td align="center">{{ $company->cover_percentage }} %</td>
                        <td align="center">{{ $company->user->name }}</td>

                        <td align="center">
                            <a href="{{ route('company.edit',['company'=>$company->id]) }}" class=" btn btn-warning">تعديل</a>
                            <a href="{{ route('company.destroy',['company'=>$company->id]) }}" class="btn btn-danger" onclick="return confirm('هل تريد أن تحذف هذه الشركة ؟')">حذف</a>
                        </td>
                    </tr>

                @empty
                    <tr colspan="4">لا توجد شركات</tr>
            @endforelse
        </table>
        <hr>
        <div class="row">
            <div class="col-2">
                <a href="{{ route('company.create') }}" class="btn btn-primary" style="margin-bottom:10px;">إضافة شركة</a>
        </div>
</div>
@endsection