routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'service',
    'as' => 'service.'

],function(){
    Route::get('/','ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::post('/store','ServiceController@store')->name('store');
    Route::get('/show/{service}','ServiceController@show')->name('show');
    Route::get('/edit/{service}','ServiceController@edit')->name('edit');
    Route::post('/update/{service}','ServiceController@update')->name('update');
    Route::get('/destroy/{service}','ServiceController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'doctor',
    'as' => 'doctor.'

],function(){
    Route::get('/','DoctorController@index')->name('index');
    Route::get('/create','DoctorController@create')->name('create');
    Route::post('/store','DoctorController@store')->name('store');
    Route::get('/ajax_res/{doctor}','DoctorController@ajax_res')->name('respond');
    Route::get('/show/{doctor}','DoctorController@show')->name('show');
    Route::get('/edit/{doctor}','DoctorController@edit')->name('edit');
    Route::post('/update/{doctor}','DoctorController@update')->name('update');
    Route::get('/destroy/{doctor}','DoctorController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'company',
    'as' => 'company.'

],function(){
    Route::get('/','CompanyController@index')->name('index');
    Route::get('/create','CompanyController@create')->name('create');
    Route::post('/store','CompanyController@store')->name('store');
    Route::get('/show/{company}','CompanyController@show')->name('show');
    Route::get('/edit/{company}','CompanyController@edit')->name('edit');
    Route::post('/update/{company}','CompanyController@update')->name('update');
    Route::get('/destroy/{company}','CompanyController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'patient',
    'as' => 'patient.'

],function(){
    Route::get('/','PatientController@index')->name('index');
    Route::get('/create','PatientController@create')->name('create');
    Route::post('/store','PatientController@store')->name('store');
    Route::get('/show/{patient}','PatientController@show')->name('show');
    Route::get('/edit/{patient}','PatientController@edit')->name('edit');
    Route::post('/update/{patient}','PatientController@update')->name('update');
    Route::get('/destroy/{patient}','PatientController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'invoice',
    'as' => 'invoice.'

],function(){
    Route::get('/','InvoiceController@index')->name('index');
    Route::get('/create/{patient}','InvoiceController@create')->name('create');
    Route::post('/store','InvoiceController@store')->name('store');
    Route::get('/show/{invoice}','InvoiceController@show')->name('show');
    Route::get('/edit/{id}','InvoiceController@edit')->name('edit');
    Route::post('/update/{id}','InvoiceController@update')->name('update');
    Route::get('/destroy/{invoice}','InvoiceController@destroy')->name('destroy');
});

app/Patient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    public function invoices() {
        return $this->hasMany(Invoice::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function company() {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Patient;
use App\Service;
use App\Doctor;
use Illuminate\Http\Request;
use Auth;

class PatientController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $patients = Patient::all();
        return view('patients.index')->with('patients', $patients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        return view('patients.create')->with('companies', $companies);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'age' => 'required | numeric',
            'gender' => 'required',
            'blood_type' => 'required'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط',
        ];

        $this->validate($request, $rules, $messages);

        $patient = new Patient;
        $patient->name = $request->input('name');
        $patient->serial_number = time();
        $patient->age = $request->input('age');
        $patient->gender = $request->input('gender');
        $patient->blood_type = $request->input('blood_type');
        $patient->company_id = $request->input('company');
        $patient->user_id = $request->input('user_id');
        $patient->save();

        return redirect()->route('patient.index')->with('success', 'تم إضافة المريض بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Patient $patient)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
       // $patient = Patient::find($id);
        $companies = Company::all();

        return view('patients.edit')->with(['patient' => $patient, 'companies' => $companies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Patient $patient)
    {
        $rules = [
            'name' => 'required',
            'age' => 'required | numeric',
            'gender' => 'required',
            'blood_type' => 'required'
        ];

        $messages = [
            'required' => 'هذا الحقل مطلوب',
            'numeric' => 'يجب أن يحتوي الحقل على أرقام فقط',
        ];

        $this->validate($request, $rules, $messages);

     //   $patient = Patient::find($id);
        $patient->name = $request->input('name');
        $patient->serial_number = time();
        $patient->age = $request->input('age');
        $patient->gender = $request->input('gender');
        $patient->blood_type = $request->input('blood_type');
        $patient->company_id = $request->input('company');
        $patient->user_id = $request->input('user_id');
        $patient->save();

        return redirect()->route('patient.index')->with('success', 'تم تخزين التعديلات بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Patient $patient)
    {
   //     $patient = Patient::find($id);
        $patient->delete();

        return redirect()->route('patient.index')->with('success', 'تم إزالة المريض بنجاح');
    }
}

resources/views/patients/create.blade.php
@extends('layouts.app')

@section('title')
    إضافة مريض
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">إضافة مريض</div>
            <div class="card-body">
            <form action="{{ route('patient.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-4">
                <label for="name" class="float-right">إسم المريض</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم المريض" value="{{ old('name') }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>

                    <div class="col-4">
                    <label for="age" class="float-right"> عمر المريض</label>
                    <input type="text" name="age" id="age" placeholder="أدخل عمر المريض" value="{{ old('age') }}" class="form-control">
                    @if ($errors->has('age'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('age') }}</strong>
                        </span>
                    @endif
                    </div>
                </div>
                <hr>
                <div class="row">

                    <div class="col-2">
                <label for="gender" class="float-right">الجنس</label>
                <select name="gender" class="form-control">
                    <option disabled selected value> -- إختر الجنس -- </option>
                    <option value="ذكر">ذكر</option>
                    <option value="أنثى">أنثى</option>
                </select>
                @if ($errors->has('gender'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('gender') }}</strong>
                        </span>
                    @endif
                    </div>

                    <div class="col-2">
                    <label for="blood_type" class="float-right"> فصيلة الدم</label>
                    <select name="blood_type" class="form-control">
                        <option disabled selected value> -- إختر فصيلة دم -- </option>
                        <option value="A+">A+</option>
                        <option value="O+">O+</option>
                        <option value="B+">B+</option>
                        <option value="AB+">AB+</option>
                        <option value="A-">A-</option>
                        <option value="O-">O-</option>
                        <option value="B-">B-</option>
                        <option value="AB-">AB-</option>
                      </select>
                      @if ($errors->has('blood_type'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('blood_type') }}</strong>
                        </span>
                    @endif
                    </div>

                    <div class="col-4">
                    <label for="company" class="float-right"> الشركة التي يتبعها</label>
                        <select name="company" class="form-control">
                            @foreach ($companies as $company)
                                <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach
                        </select>
                        <span class="float-right alert-warning">
                                <strong>إذا لم يتم اختيار شركة , سيتم اعتبار المريض بأنه لا يتبع أي شركة </strong>
                        </span>
                    </div>
                </div>
            </div>
            <hr>
                <div class="col-2">
                <input type="hidden" name="user_id" value="{{Auth::id()}}">
                <input type="submit" value="حفظ" class="form-control btn btn-primary">
                </div>
                <hr>
            </form>
            </div>
    </div>
@endsection

resources/views/patients/edit.blade.php
@extends('layouts.app')

@section('title')
    تعديل مريض
@endsection

@section('content')
    <div class="container card" dir="rtl">
        <div class="card-header">تعديل مريض</div>
            <div class="card-body">
            <form action="{{ route('patient.update',['id'=>$patient->id]) }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-4">
                <label for="name" class="float-right">إسم المريض</label>
                <input type="text" name="name" id="name" placeholder="أدخل اسم المريض" value="{{ $patient->name }}" class="form-control">
                @if ($errors->has('name'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                @endif
                    </div>

                    <div class="col-4">
                    <label for="age" class="float-right"> عمر المريض</label>
                    <input type="text" name="age" id="age" placeholder="أدخل عمر المريض" value="{{ $patient->age }}" class="form-control">
                    @if ($errors->has('age'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('age') }}</strong>
                        </span>
                    @endif
                    </div>
                </div>
                <hr>
                <div class="row">

                    <div class="col-2">
                <label for="gender" class="float-right">الجنس</label>
                <select name="gender" class="form-control">
                    <option disabled selected value> -- إختر الجنس -- </option>
                    <option value="ذكر">ذكر</option>
                    <option value="أنثى">أنثى</option>
                </select>
                @if ($errors->has('gender'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('gender') }}</strong>
                        </span>
                    @endif
                    </div>

                    <div class="col-2">
                    <label for="blood_type" class="float-right"> فصيلة الدم</label>
                    <select name="blood_type" class="form-control">
                        <option disabled selected value> -- إختر فصيلة دم -- </option>
                        <option value="A+">A+</option>
                        <option value="O+">O+</option>
                        <option value="B+">B+</option>
                        <option value="AB+">AB+</option>
                        <option value="A-">A-</option>
                        <option value="O-">O-</option>
                        <option value="B-">B-</option>
                        <option value="AB-">AB-</option>
                      </select>
                      @if ($errors->has('blood_type'))
                        <span class="float-right alert-danger">
                            <strong>{{ $errors->first('blood_type') }}</strong>
                        </span>
                    @endif
                    </div>

                    <div class="col-4">
                    <label for="company" class="float-right"> الشركة التي يتبعها</label>

                        <select name="company" class="form-control">
                            @foreach ($companies as $company)
                                <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach
                        </select>
                        <span class="float-right alert-warning">
                                <strong>إذا لم يتم اختيار شركة , سيتم اعتبار المريض بأنه لا يتبع أي شركة </strong>
                            </span>
                    </div>
                </div>
            </div>
            <hr>
                <div class="col-2">
                <input type="hidden" name="user_id" value="{{Auth::id()}}">
                <input type="submit" value="حفظ" class="form-control btn btn-primary">
                </div>

            </form>
            </div>
    </div>
@endsection

resources/views/patients/index.blade.php
@extends('layouts.app')

@section('title')
    المرضى
@endsection
@section('content')

<div class="container card" dir="rtl">
    <table class="table table-striped table-bordered" style="margin-bottom: 0px; margin-top: 10px;">
        <tr>
            <td align="center"><strong>#</strong></td>
            <td align="center"><strong>الإسم</strong></th>
            <td align="center"><strong>العمر</strong></td>
            <td align="center"><strong>الرقم التسلسلي</strong></td>
            <td align="center"><strong>أُضيف بواسطة</strong></td>
            <td align="center"><strong>الجنس</strong></td>
            <td align="center"><strong>فصيلة الدم</strong></td>
            <td align="center"><strong>الشركة الذي يتبعها</strong></td>
            <td align="center"><strong>عمليات</strong></td>
        </tr>
        @forelse ($patients as $patient)

                    <tr>
                        <td align="center">{{ ++$loop->index }}</td>
                        <td align="center">{{ $patient->name }}</td>
                        <td align="center">{{ $patient->age }}</td>
                        <td align="center">{{ $patient->serial_number }}</td>
                        <td align="center">{{ $patient->user->name }}</td>
                        <td align="center">{{ $patient->gender }}</td>
                        <td align="center">{{ $patient->blood_type}}</td>
                        <td align="center">{{ $patient->company->name}}</td>

                        <td align="center">
                            <a href="{{ route('patient.edit',['patient'=>$patient->id]) }}" class=" btn btn-warning">تعديل</a>
                            <a href="{{ route('patient.destroy',['patient'=>$patient->id]) }}" class="btn btn-danger" onclick="return confirm('هل تريد أن تحذف هذا المريض ؟')">حذف</a>
                            <a href="{{ route('invoice.create',['patient'=>$patient->id]) }}" class=" btn btn-primary">إصدار فاتورة</a>
                        </td>
                    </tr>

                @empty
                    <tr colspan="4">لا يوجد مرضى</tr>
            @endforelse
        </table>
        <hr>
        <div class="row">
                <div class="col-2">
                        <a href="{{ route('patient.create') }}" class="btn btn-primary" style="margin-bottom: 10px;" >إضافة مريض</a>
                </div>
        </div>
</div>
@endsection